# Generated by Django 4.2.2 on 2024-08-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.TextField(blank=True, null=True, verbose_name="Токен"),
        ),
    ]
