# Generated by Django 5.0.7 on 2024-08-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="book_return_date",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата возврата книги"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_the_book_was_taken",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата выдачи книги"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_when_the_book_was_returned",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Дата возврата книги"
            ),
        ),
    ]
