version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  library:
    build:
      context: .
    tty: true
    volumes:
      - .:/app
    restart: on-failure
    ports:
      - "8000:8000"
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis
    ports:
      - "6380:6379"
    restart: on-failure

volumes:
  pg_data: